apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: user-service
  name: user-service
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: user-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: user-service
    spec:
      containers:
      - image: it19108582/user-service:f2ef63a1812e2ea3142e00b860d5fec7e24a0a3e
        imagePullPolicy: Always
        name: user-service
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
        - containerPort: 8070
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}