apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: ctse-usermanagement
  name: ctse-usermanagement
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ctse-usermanagement
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ctse-usermanagement
    spec:
      containers:
      - image: it19108582/ctse:f5a02c4856ff52cb32bb92262d7a861a68c13278
        imagePullPolicy: Always
        name: ctse
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
        - containerPort: 8070
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}